service: allowlist-api

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:987989283142:simoteam-test.fifo"
  memorySize: 4086
  timeout: 900
  cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
            - "sqs:GetQueueAttributes"
            - "sqs:DeleteMessage"
          Resource: arn:aws:sqs:*:*:*
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetRandomPassword"
            - "secretsmanager:GetResourcePolicy"
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:DescribeSecret"
            - "secretsmanager:ListSecretVersionIds"
            - "secretsmanager:ListSecrets"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: "arn:aws:sns:us-east-1:987989283142:simoteam-test.fifo"

custom:
  warmup:
    default:
      enabled: false
  optimize:
    external:
      [
        'axios',
        'form-data',
        'combined-stream',
        'delayed-stream',
        'mime-types',
        'mime-db',
        'asynckit',
        'proxy-from-env',
        'follow-redirects',
      ]
    includePaths:
      [
        'node_modules/axios',
        'node_modules/form-data',
        'node_modules/combined-stream',
        'node_modules/delayed-stream',
        'node_modules/mime-types',
        'node_modules/mime-db',
        'node_modules/asynckit',
        'node_modules/proxy-from-env',
        'node_modules/follow-redirects',
      ]

functions:
  main:
    handler: ./src/api-lambda.handler
    timeout: 120
    events:
      - http:
          method: any
          path: /{any+}
  queue:
    handler: src/worker-lambda.handler