export enum TokenPoolDownloadStage {
  PREPARING = 'PREPARING',
  REQUEUED = 'REQUEUED',
  CLAIMED = 'CLAIMED',
  CHECKING_ALCHEMY = 'CHECKING_ALCHEMY',
  INDEXING_SINGLE = 'INDEXING_SINGLE',
  INDEXING_BATCH = 'INDEXING_BATCH',
  BUILDING_TOKEN_OWNERS = 'BUILDING_TOKEN_OWNERS',
  PERSISTING_RESULTS = 'PERSISTING_RESULTS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
