name: Allowlist API Ci

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run unit tests
        run: yarn test